/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb95f',
        'outline-variant': '#3b4a46',
        'primary-fixed-dim': '#00dfc5',
        'surface-container-lowest': '#0a0e13',
        'primary': '#4cffe4',
        'tertiary-fixed': '#ffddb8',
        'on-background': '#e0e2ea',
        'surface-bright': '#36393f',
        'surface-tint': '#00dfc5',
        'on-tertiary': '#472a00',
        'secondary': '#b4c5ff',
        'surface-container': '#1c2025',
        'on-secondary': '#002a78',
        'background': '#101419',
        'outline': '#849490',
        'secondary-container': '#0053db',
        'on-tertiary-fixed': '#2a1700',
        'surface-dim': '#101419',
        'on-primary-fixed-variant': '#005046',
        'primary-container': '#0ae2c8',
        'on-primary-fixed': '#00201b',
        'secondary-fixed': '#dbe1ff',
        'on-secondary-fixed-variant': '#003ea8',
        'on-secondary-container': '#cdd7ff',
        'on-primary': '#003730',
        'surface-container-low': '#181c21',
        'on-surface-variant': '#bacac5',
        'inverse-on-surface': '#2d3136',
        'tertiary-container': '#ffbd6a',
        'tertiary': '#ffe1c1',
        'inverse-surface': '#e0e2ea',
        'surface': '#101419',
        'on-error': '#690005',
        'surface-container-highest': '#31353b',
        'surface-variant': '#31353b',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#653e00',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#006b5e',
        'on-tertiary-container': '#784b00',
        'error': '#ffb4ab',
        'on-secondary-fixed': '#00174b',
        'secondary-fixed-dim': '#b4c5ff',
        'surface-container-high': '#262a30',
        'on-primary-container': '#006054',
        'on-surface': '#e0e2ea',
        'primary-fixed': '#47fce1'
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem'
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'space-4xl': '6rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'margin-mobile': '1rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem'
      },
      fontFamily: {
        'headline-2xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-2xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['Inter', 'sans-serif'],
        'code-lg': ['"JetBrains Mono"', 'monospace'],
        'code-md': ['"JetBrains Mono"', 'monospace']
      }
    }
  },
  plugins: [],
};