SYMPTOMS_TAXONOMY = [
    # 1. Pulmonology & Airway (8)
    {
        "id": "persistent_dry_cough",
        "code": "RESP-01",
        "name": "Persistent Dry Cough",
        "category": "Pulmonology & Airway",
        "anatomical_region": "chest",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Non-productive irritant cough originating from tracheobronchial inflammation."
    },
    {
        "id": "productive_cough_sputum",
        "code": "RESP-02",
        "name": "Cough with Productive Sputum",
        "category": "Pulmonology & Airway",
        "anatomical_region": "chest",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Expectoration of mucous or purulent secretions from lower respiratory airways."
    },
    {
        "id": "wheezing_bronchospasm",
        "code": "RESP-03",
        "name": "Wheezing & Bronchospasm",
        "category": "Pulmonology & Airway",
        "anatomical_region": "chest",
        "default_severity": 7,
        "is_red_flag": False,
        "description": "High-pitched musical adventitious sound heard during exhalation due to airway narrowing."
    },
    {
        "id": "dyspnea_shortness_breath",
        "code": "RESP-04",
        "name": "Shortness of Breath (Dyspnea)",
        "category": "Pulmonology & Airway",
        "anatomical_region": "chest",
        "default_severity": 8,
        "is_red_flag": True,
        "description": "Subjective sensation of uncomfortable or difficult breathing at rest or minimal exertion."
    },
    {
        "id": "chest_tightness_exertion",
        "code": "RESP-05",
        "name": "Chest Tightness on Exertion",
        "category": "Pulmonology & Airway",
        "anatomical_region": "chest",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Sensation of thoracic constriction occurring during physical activity or airway irritation."
    },
    {
        "id": "sore_throat_pharyngitis",
        "code": "RESP-06",
        "name": "Sore Throat & Odynophagia",
        "category": "Pulmonology & Airway",
        "anatomical_region": "chest",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Pain or scratchy sensation in the pharynx intensified by swallowing."
    },
    {
        "id": "hoarseness_stridor",
        "code": "RESP-07",
        "name": "Hoarseness / Vocal Strain",
        "category": "Pulmonology & Airway",
        "anatomical_region": "chest",
        "default_severity": 4,
        "is_red_flag": False,
        "description": "Dysphonia resulting from laryngeal mucosal irritation or acute vocal cord edema."
    },
    {
        "id": "tachypnea_rapid_breathing",
        "code": "RESP-08",
        "name": "Rapid Shallow Breathing (Tachypnea)",
        "category": "Pulmonology & Airway",
        "anatomical_region": "chest",
        "default_severity": 7,
        "is_red_flag": True,
        "description": "Respiratory rate exceeding 22 breaths per minute accompanied by shallow ventilation."
    },

    # 2. Cranial & Neurological (8)
    {
        "id": "frontal_tension_headache",
        "code": "CRAN-01",
        "name": "Bilateral Frontal Tension Headache",
        "category": "Cranial & Neurological",
        "anatomical_region": "head",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Constricting band-like pressure across forehead and occipital regions."
    },
    {
        "id": "throbbing_migraine",
        "code": "CRAN-02",
        "name": "Unilateral Throbbing Migraine",
        "category": "Cranial & Neurological",
        "anatomical_region": "head",
        "default_severity": 7,
        "is_red_flag": False,
        "description": "Pulsating hemicranial discomfort exacerbated by physical motion or acoustic stimuli."
    },
    {
        "id": "dizziness_vertigo",
        "code": "CRAN-03",
        "name": "Dizziness & Vestibular Vertigo",
        "category": "Cranial & Neurological",
        "anatomical_region": "head",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Sensation of spinning, postural instability, or faint equilibrium disturbance."
    },
    {
        "id": "visual_aura_photophobia",
        "code": "CRAN-04",
        "name": "Visual Aura & Photophobia",
        "category": "Cranial & Neurological",
        "anatomical_region": "head",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Transient scintillating scotoma or uncomfortable hypersensitivity to ambient illumination."
    },
    {
        "id": "cognitive_fog_fatigue",
        "code": "CRAN-05",
        "name": "Cognitive Fog & Concentration Lag",
        "category": "Cranial & Neurological",
        "anatomical_region": "head",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Subjective reduction in mental clarity, sluggish executive processing, or mental exhaustion."
    },
    {
        "id": "facial_sinus_pressure",
        "code": "CRAN-06",
        "name": "Maxillary & Frontal Sinus Pressure",
        "category": "Cranial & Neurological",
        "anatomical_region": "head",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Dull aching heaviness over the paranasal sinuses worsened when bending forward."
    },
    {
        "id": "anosmia_loss_smell",
        "code": "CRAN-07",
        "name": "Anosmia / Loss of Olfactory Sensation",
        "category": "Cranial & Neurological",
        "anatomical_region": "head",
        "default_severity": 4,
        "is_red_flag": False,
        "description": "Partial or complete sudden deficit in olfactory discrimination without total nasal occlusion."
    },
    {
        "id": "syncope_presyncope",
        "code": "CRAN-08",
        "name": "Presyncope / Sudden Lightheadedness",
        "category": "Cranial & Neurological",
        "anatomical_region": "head",
        "default_severity": 8,
        "is_red_flag": True,
        "description": "Acute sensation of impending loss of consciousness with blurred vision and diaphoresis."
    },

    # 3. Cardiovascular & Thoracic (8)
    {
        "id": "palpitations_tachycardia",
        "code": "CARD-01",
        "name": "Heart Palpitations & Tachycardia",
        "category": "Cardiovascular & Thoracic",
        "anatomical_region": "chest",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Awareness of pounding, skipping, or racing cardiac beats at resting state."
    },
    {
        "id": "retrosternal_chest_pressure",
        "code": "CARD-02",
        "name": "Retrosternal Chest Pain / Pressure",
        "category": "Cardiovascular & Thoracic",
        "anatomical_region": "chest",
        "default_severity": 9,
        "is_red_flag": True,
        "description": "Crushing, squeezing, or substernal heavy ache requiring immediate diagnostic exclusion."
    },
    {
        "id": "radiating_arm_jaw_pain",
        "code": "CARD-03",
        "name": "Radiating Left Arm or Jaw Pain",
        "category": "Cardiovascular & Thoracic",
        "anatomical_region": "chest",
        "default_severity": 10,
        "is_red_flag": True,
        "description": "Discomfort radiating into left shoulder, arm, neck, or lower mandibular boundary."
    },
    {
        "id": "peripheral_cyanosis",
        "code": "CARD-04",
        "name": "Peripheral Cyanosis (Bluish Lips/Nails)",
        "category": "Cardiovascular & Thoracic",
        "anatomical_region": "chest",
        "default_severity": 10,
        "is_red_flag": True,
        "description": "Bluish or violaceous discoloration of mucosal borders indicating arterial hypoxemia."
    },
    {
        "id": "cold_diaphoresis",
        "code": "CARD-05",
        "name": "Cold Clammy Diaphoresis",
        "category": "Cardiovascular & Thoracic",
        "anatomical_region": "chest",
        "default_severity": 7,
        "is_red_flag": True,
        "description": "Profuse cold perspiration accompanying systemic distress or acute autonomic activation."
    },
    {
        "id": "orthopnea_paroxysmal",
        "code": "CARD-06",
        "name": "Orthopnea (Breathlessness Lying Flat)",
        "category": "Cardiovascular & Thoracic",
        "anatomical_region": "chest",
        "default_severity": 7,
        "is_red_flag": False,
        "description": "Shortness of breath precipitated in the supine position relieved by elevation."
    },
    {
        "id": "bilateral_ankle_edema",
        "code": "CARD-07",
        "name": "Bilateral Dependent Ankle Swelling",
        "category": "Cardiovascular & Thoracic",
        "anatomical_region": "joints",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Pitting fluid retention in lower extremities worsening toward evening."
    },
    {
        "id": "pleuritic_chest_stitch",
        "code": "CARD-08",
        "name": "Pleuritic Sharp Chest Pain",
        "category": "Cardiovascular & Thoracic",
        "anatomical_region": "chest",
        "default_severity": 7,
        "is_red_flag": False,
        "description": "Sharp knife-like focal chest pain aggravated by deep inspiration or coughing."
    },

    # 4. Gastrointestinal & Hepatic (8)
    {
        "id": "epigastric_pyrosis_reflux",
        "code": "GAST-01",
        "name": "Epigastric Burning & Acid Reflux",
        "category": "Gastrointestinal & Hepatic",
        "anatomical_region": "abdomen",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Substernal retrograde burning sensation radiating upward into cervical esophagus."
    },
    {
        "id": "nausea_emesis",
        "code": "GAST-02",
        "name": "Nausea & Occasional Emesis",
        "category": "Gastrointestinal & Hepatic",
        "anatomical_region": "abdomen",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Sensation of gastric revulsion with voluntary or involuntary gastroesophageal expulsion."
    },
    {
        "id": "abdominal_cramping",
        "code": "GAST-03",
        "name": "Spasmodic Abdominal Cramps",
        "category": "Gastrointestinal & Hepatic",
        "anatomical_region": "abdomen",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Colicky visceral contractions throughout periumbilical or lower abdominal quadrants."
    },
    {
        "id": "diarrhea_enteritis",
        "code": "GAST-04",
        "name": "Watery Diarrhea / Loose Stools",
        "category": "Gastrointestinal & Hepatic",
        "anatomical_region": "abdomen",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Frequent evacuations of unformed liquid stools resulting from mucosal irritation."
    },
    {
        "id": "bloating_meteorism",
        "code": "GAST-05",
        "name": "Abdominal Distension & Bloating",
        "category": "Gastrointestinal & Hepatic",
        "anatomical_region": "abdomen",
        "default_severity": 4,
        "is_red_flag": False,
        "description": "Subjective tightness with visible gas retention and luminal hyperresonance."
    },
    {
        "id": "ruq_hepatic_tenderness",
        "code": "GAST-06",
        "name": "Right Upper Quadrant Tenderness",
        "category": "Gastrointestinal & Hepatic",
        "anatomical_region": "abdomen",
        "default_severity": 7,
        "is_red_flag": False,
        "description": "Discomfort elicited over biliary and hepatic anatomical boundaries."
    },
    {
        "id": "early_satiety_dyspepsia",
        "code": "GAST-07",
        "name": "Early Satiety & Postprandial Fullness",
        "category": "Gastrointestinal & Hepatic",
        "anatomical_region": "abdomen",
        "default_severity": 4,
        "is_red_flag": False,
        "description": "Inability to consume regular meal volumes due to rapid sensation of gastric repleteness."
    },
    {
        "id": "constipation_slow_transit",
        "code": "GAST-08",
        "name": "Obstipation / Infrequent Bowel Transit",
        "category": "Gastrointestinal & Hepatic",
        "anatomical_region": "abdomen",
        "default_severity": 4,
        "is_red_flag": False,
        "description": "Straining during defecation with decreased weekly frequency."
    },

    # 5. Musculoskeletal & Articular (8)
    {
        "id": "knee_arthralgia_joint_pain",
        "code": "MUSC-01",
        "name": "Peripheral Joint Arthralgia (Knees/Wrists)",
        "category": "Musculoskeletal & Articular",
        "anatomical_region": "joints",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Dull or throbbing ache located within synovial joint capsules during weight-bearing."
    },
    {
        "id": "morning_joint_stiffness",
        "code": "MUSC-02",
        "name": "Morning Articular Stiffness (>30 min)",
        "category": "Musculoskeletal & Articular",
        "anatomical_region": "joints",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Impaired flexibility and mechanical resistance to joint mobilization upon awakening."
    },
    {
        "id": "generalized_myalgia",
        "code": "MUSC-03",
        "name": "Generalized Diffuse Myalgia (Muscle Aches)",
        "category": "Musculoskeletal & Articular",
        "anatomical_region": "joints",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Widespread tender muscular soreness characteristic of viral cytokine dissemination."
    },
    {
        "id": "nuchal_rigidity_neck_stiffness",
        "code": "MUSC-04",
        "name": "Acute Neck Stiffness (Nuchal Rigidity)",
        "category": "Musculoskeletal & Articular",
        "anatomical_region": "head",
        "default_severity": 9,
        "is_red_flag": True,
        "description": "Severe resistance to passive cervical flexion; warning sign for meningeal irritation."
    },
    {
        "id": "lumbar_paraspinal_strain",
        "code": "MUSC-05",
        "name": "Lumbar Paraspinal Soreness",
        "category": "Musculoskeletal & Articular",
        "anatomical_region": "joints",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Mechanical muscular ache localized to lumbosacral paraspinal fascial planes."
    },
    {
        "id": "joint_effusion_swelling",
        "code": "MUSC-06",
        "name": "Joint Effusion / Visible Swelling",
        "category": "Musculoskeletal & Articular",
        "anatomical_region": "joints",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Intra-articular fluid buildup resulting in visible swelling and decreased range of motion."
    },
    {
        "id": "muscle_tremor_fasciculation",
        "code": "MUSC-07",
        "name": "Muscle Fasciculations / Fine Tremor",
        "category": "Musculoskeletal & Articular",
        "anatomical_region": "joints",
        "default_severity": 4,
        "is_red_flag": False,
        "description": "Involuntary spontaneous contractions of individual motor units."
    },
    {
        "id": "shoulder_glenohumeral_limitation",
        "code": "MUSC-08",
        "name": "Shoulder Range-of-Motion Limitation",
        "category": "Musculoskeletal & Articular",
        "anatomical_region": "joints",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Painful restriction during abduction or external rotation of humeral head."
    },

    # 6. Systemic & Thermal (8)
    {
        "id": "low_grade_fever",
        "code": "SYST-01",
        "name": "Low-Grade Pyrexia (37.8°C - 38.4°C)",
        "category": "Systemic & Thermal",
        "anatomical_region": "general",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Mild elevation in core thermoregulatory set-point reflecting viral host response."
    },
    {
        "id": "uncontrolled_hyperpyrexia",
        "code": "SYST-02",
        "name": "High Uncontrolled Fever (>39.5°C)",
        "category": "Systemic & Thermal",
        "anatomical_region": "general",
        "default_severity": 9,
        "is_red_flag": True,
        "description": "Marked thermal elevation unresponsive to standard antipyretics or causing delirium."
    },
    {
        "id": "physical_fatigue_malaise",
        "code": "SYST-03",
        "name": "Physical Fatigue & Malaise",
        "category": "Systemic & Thermal",
        "anatomical_region": "general",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Overwhelming lethargy, subjective energy depletion, and generalized unfitness."
    },
    {
        "id": "shivering_rigors_chills",
        "code": "SYST-04",
        "name": "Shivering Rigors & Chills",
        "category": "Systemic & Thermal",
        "anatomical_region": "general",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Involuntary muscular paroxysms associated with rapid core body temperature elevation."
    },
    {
        "id": "nocturnal_diaphoresis",
        "code": "SYST-05",
        "name": "Drenching Night Sweats",
        "category": "Systemic & Thermal",
        "anatomical_region": "general",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Severe perspiration during sleep requiring changing of bed clothing."
    },
    {
        "id": "xerostomia_dehydration",
        "code": "SYST-06",
        "name": "Dry Mucous Membranes & Thirst",
        "category": "Systemic & Thermal",
        "anatomical_region": "general",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Signs of extracellular fluid deficit, decreased salivary output, and dry tongue."
    },
    {
        "id": "unintentional_weight_loss",
        "code": "SYST-07",
        "name": "Unintentional Weight Loss",
        "category": "Systemic & Thermal",
        "anatomical_region": "general",
        "default_severity": 6,
        "is_red_flag": False,
        "description": "Loss of body mass exceeding 5% over 3 months without voluntary caloric reduction."
    },
    {
        "id": "lymphadenopathy_cervical",
        "code": "SYST-08",
        "name": "Tender Cervical Lymphadenopathy",
        "category": "Systemic & Thermal",
        "anatomical_region": "head",
        "default_severity": 5,
        "is_red_flag": False,
        "description": "Palpable enlargement and tenderness of anterior or posterior cervical lymph nodes."
    }
]

# 30 Clinical Target Conditions with standard diagnostic profiles & layperson explanations
CONDITIONS_PROFILES = [
    {
        "id": "viral_bronchitis",
        "name": "Acute Viral Bronchitis / Upper Respiratory Tract Syndrome",
        "simple_name": "Chest Cold (Bronchitis)",
        "simple_explanation": "An inflammation of your lungs' main airways, usually caused by a cold virus. It causes a nagging cough, mild chest tightness, and fatigue, but typically clears up in 1 to 2 weeks.",
        "icd10": "J20.9",
        "primary_system": "Tracheobronchial Tree",
        "natural_duration": "7 — 14 Days (Self-limiting gradual resolution)",
        "action_level": "Supportive Care & Hydration",
        "action_level_desc": "Antitussive if sleep disrupted; monitor oral temperature; fluid loading.",
        "key_symptoms": ["persistent_dry_cough", "low_grade_fever", "physical_fatigue_malaise", "chest_tightness_exertion"],
        "unreported_common": ["productive_cough_sputum", "shivering_rigors_chills", "dyspnea_shortness_breath"],
        "prevention": "Hand hygiene, adequate sleep, air humidification, avoid tobacco smoke."
    },
    {
        "id": "allergic_rhinitis",
        "name": "Seasonal Allergenic Rhinotracheitis",
        "simple_name": "Seasonal Allergies (Hay Fever)",
        "simple_explanation": "An allergic reaction to airborne particles like pollen or dust, causing sneezing, sinus pressure, a scratchy throat, and clear nasal drainage.",
        "icd10": "J30.2",
        "primary_system": "Upper Nasopharyngeal Mucosa",
        "natural_duration": "2 — 4 Weeks (Persists through allergen exposure)",
        "action_level": "Allergen Avoidance / H1-Blocker",
        "action_level_desc": "Intranasal glucocorticoid review with PCP; avoid known environmental triggers.",
        "key_symptoms": ["persistent_dry_cough", "facial_sinus_pressure", "sore_throat_pharyngitis", "visual_aura_photophobia"],
        "unreported_common": ["low_grade_fever", "shivering_rigors_chills", "productive_cough_sputum"],
        "prevention": "HEPA air filtration, avoid pollen during peak windy morning hours."
    },
    {
        "id": "atypical_pneumonia",
        "name": "Early Pneumonic Infiltration (Atypical)",
        "simple_name": "Walking Pneumonia",
        "simple_explanation": "A mild lung infection that causes a persistent dry cough, shortness of breath, and deep chest tightness, but usually allows you to stay active while recovering.",
        "icd10": "J18.9",
        "primary_system": "Alveolar Parenchyma & Interstitium",
        "natural_duration": "Variable / Progressive (Requires direct clinical exam)",
        "action_level": "Auscultation & Direct Exam",
        "action_level_desc": "Evaluate with physician if fever accelerates or exertional breathlessness persists.",
        "key_symptoms": ["persistent_dry_cough", "dyspnea_shortness_breath", "physical_fatigue_malaise", "pleuritic_chest_stitch"],
        "unreported_common": ["productive_cough_sputum", "radiating_arm_jaw_pain", "wheezing_bronchospasm"],
        "prevention": "Pneumococcal immunization adherence, early attention to protracted viral bronchitis."
    },
    {
        "id": "influenza_respiratory",
        "name": "Acute Influenza Viral Syndrome (Type A/B)",
        "simple_name": "Flu (Influenza)",
        "simple_explanation": "A contagious viral infection that comes on suddenly with high fever, chills, intense body aches, dry cough, and exhaustion.",
        "icd10": "J11.1",
        "primary_system": "Systemic Respiratory Epithelium",
        "natural_duration": "5 — 10 Days (Acute peak at 48-72 hours)",
        "action_level": "Rest, Hydration & Antiviral Window",
        "action_level_desc": "Evaluate within 48h if candidate for neuraminidase inhibitors; isolate from vulnerable individuals.",
        "key_symptoms": ["shivering_rigors_chills", "generalized_myalgia", "low_grade_fever", "physical_fatigue_malaise", "persistent_dry_cough"],
        "unreported_common": ["epigastric_pyrosis_reflux", "diarrhea_enteritis", "bilateral_ankle_edema"],
        "prevention": "Annual quadrivalent influenza vaccination, respiratory hygiene."
    },
    {
        "id": "acute_sinusitis",
        "name": "Acute Maxillary Rhino-Sinusitis",
        "simple_name": "Sinus Infection",
        "simple_explanation": "Swelling and pressure in the sinus cavities around your forehead and cheeks, leading to facial fullness, headache, and nasal congestion.",
        "icd10": "J01.9",
        "primary_system": "Paranasal Sinus Cavities",
        "natural_duration": "7 — 10 Days (Bacterial consideration if >10 days)",
        "action_level": "Nasal Saline & Decongestant",
        "action_level_desc": "Twice daily hypertonic saline irrigation; monitor for periorbital erythema.",
        "key_symptoms": ["facial_sinus_pressure", "frontal_tension_headache", "anosmia_loss_smell", "low_grade_fever"],
        "unreported_common": ["dyspnea_shortness_breath", "pleuritic_chest_stitch", "knee_arthralgia_joint_pain"],
        "prevention": "Prompt management of allergic flares, humidification."
    },
    {
        "id": "common_cold_rhinovirus",
        "name": "Acute Rhinovirus Nasopharyngitis (Common Cold)",
        "simple_name": "Common Cold",
        "simple_explanation": "A harmless viral infection of the nose and throat causing a sore throat, mild cough, runny nose, and mild tiredness.",
        "icd10": "J06.9",
        "primary_system": "Upper Airway Mucosa",
        "natural_duration": "5 — 7 Days (Rapid viral clearance)",
        "action_level": "Symptomatic Care",
        "action_level_desc": "Throat lozenges, warm tea, nasal mist, rest.",
        "key_symptoms": ["sore_throat_pharyngitis", "persistent_dry_cough", "facial_sinus_pressure", "physical_fatigue_malaise"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "dyspnea_shortness_breath", "retrosternal_chest_pressure"],
        "prevention": "Frequent handwashing, avoidance of facial touch."
    },
    {
        "id": "strep_pharyngitis",
        "name": "Acute Streptococcal Pharyngotonsillitis",
        "simple_name": "Strep Throat",
        "simple_explanation": "A bacterial infection of the throat and tonsils causing severe pain when swallowing, swollen neck glands, and fever.",
        "icd10": "J02.0",
        "primary_system": "Tonsillar & Oropharyngeal Lymphatics",
        "natural_duration": "3 — 7 Days (Antimicrobial intervention shortens course)",
        "action_level": "Centor Criteria & Rapid Antigen Test",
        "action_level_desc": "Visit clinic for throat swab to determine antibiotic indication and prevent rheumatic sequelae.",
        "key_symptoms": ["sore_throat_pharyngitis", "lymphadenopathy_cervical", "low_grade_fever", "shivering_rigors_chills"],
        "unreported_common": ["persistent_dry_cough", "wheezing_bronchospasm", "diarrhea_enteritis"],
        "prevention": "Avoid sharing cups/utensils with symptomatic individuals."
    },
    {
        "id": "covid19_variant",
        "name": "SARS-CoV-2 Upper Variant Syndrome",
        "simple_name": "COVID-19 Respiratory Infection",
        "simple_explanation": "A viral respiratory infection that can cause loss of taste or smell, sore throat, cough, muscle aches, and fever.",
        "icd10": "U07.1",
        "primary_system": "Endothelial & Mucosal Cascade",
        "natural_duration": "7 — 14 Days (Variable trajectory)",
        "action_level": "Home Antigen Test & SpO2 Surveillance",
        "action_level_desc": "Confirm with rapid lateral flow test; isolate; track oxygen saturation with pulse oximeter.",
        "key_symptoms": ["anosmia_loss_smell", "sore_throat_pharyngitis", "persistent_dry_cough", "physical_fatigue_malaise", "generalized_myalgia"],
        "unreported_common": ["ruq_hepatic_tenderness", "radiating_arm_jaw_pain"],
        "prevention": "Updated variant booster immunization, well-fitted masking in crowded spaces."
    },
    {
        "id": "gerd_reflux",
        "name": "Gastroesophageal Reflux Disease (GERD)",
        "simple_name": "Acid Reflux / Heartburn",
        "simple_explanation": "Stomach acid flowing back up into your esophagus, causing a burning feeling in the upper stomach or chest, throat irritation, and bloating.",
        "icd10": "K21.9",
        "primary_system": "Lower Esophageal Sphincter",
        "natural_duration": "Chronic / Recurrent postprandial episodes",
        "action_level": "Dietary Adjustment & H2RA / PPI Trial",
        "action_level_desc": "Elevate head of bed 15 degrees; avoid eating within 3 hours of sleep; minimize citrus/caffeine.",
        "key_symptoms": ["epigastric_pyrosis_reflux", "persistent_dry_cough", "hoarseness_stridor", "bloating_meteorism"],
        "unreported_common": ["low_grade_fever", "shivering_rigors_chills", "generalized_myalgia"],
        "prevention": "Smaller frequent meals, weight optimization, smoking cessation."
    },
    {
        "id": "viral_gastroenteritis",
        "name": "Acute Viral Gastroenteritis (Norovirus / Rotavirus)",
        "simple_name": "Stomach Flu (Gastroenteritis)",
        "simple_explanation": "A short-lived intestinal virus that causes nausea, vomiting, watery diarrhea, stomach cramps, and mild fever.",
        "icd10": "A08.4",
        "primary_system": "Enteric Epithelium",
        "natural_duration": "24 — 72 Hours (Acute self-limiting)",
        "action_level": "Oral Rehydration Salt (ORS) Therapy",
        "action_level_desc": "Replenish sodium/potassium loss; avoid dairy and fatty foods until 24h post-emesis.",
        "key_symptoms": ["nausea_emesis", "diarrhea_enteritis", "abdominal_cramping", "low_grade_fever", "physical_fatigue_malaise"],
        "unreported_common": ["persistent_dry_cough", "facial_sinus_pressure", "wheezing_bronchospasm"],
        "prevention": "Strict food safety, bleach-based disinfection of shared surfaces."
    },
    {
        "id": "tension_headache",
        "name": "Episodic Tension-Type Cephalea",
        "simple_name": "Tension Headache",
        "simple_explanation": "A tight, band-like dull headache across the forehead or back of the head, often triggered by stress, screen strain, or bad posture.",
        "icd10": "G44.2",
        "primary_system": "Pericranial Myofascial Tone",
        "natural_duration": "30 min — Several Hours",
        "action_level": "Ergonomic & Hydration Correction",
        "action_level_desc": "Take screen breaks; evaluate cervical posture; mild OTC analgesia if necessary.",
        "key_symptoms": ["frontal_tension_headache", "lumbar_paraspinal_strain", "cognitive_fog_fatigue"],
        "unreported_common": ["low_grade_fever", "nausea_emesis", "radiating_arm_jaw_pain"],
        "prevention": "Regular circadian sleep rhythm, posture exercises."
    },
    {
        "id": "migraine_with_aura",
        "name": "Migraine Cephalea with Sensory Aura",
        "simple_name": "Migraine Headache",
        "simple_explanation": "An intense, throbbing headache on one side of the head, often preceded by visual spots or light sensitivity and accompanied by nausea.",
        "icd10": "G43.1",
        "primary_system": "Trigeminovascular System",
        "natural_duration": "4 — 72 Hours per episode",
        "action_level": "Dark Quiet Room & Triptan / NSAID Window",
        "action_level_desc": "Retire to a dark stimulus-free room; take prescribed abortive therapy early in aura phase.",
        "key_symptoms": ["throbbing_migraine", "visual_aura_photophobia", "nausea_emesis", "dizziness_vertigo"],
        "unreported_common": ["low_grade_fever", "productive_cough_sputum", "pleuritic_chest_stitch"],
        "prevention": "Identify migraine triggers (aged cheese, nitrate additives, skipped meals)."
    },
    {
        "id": "costochondritis",
        "name": "Costochondral Joint Inflammation (Costochondritis)",
        "simple_name": "Chest Wall Muscle/Rib Inflammation",
        "simple_explanation": "Inflammation of the cartilage connecting your ribs to your breastbone, causing sharp chest pain when breathing deeply or pushing on the chest.",
        "icd10": "M94.0",
        "primary_system": "Costosternal Cartilaginous Junction",
        "natural_duration": "1 — 3 Weeks (Gradual resolution)",
        "action_level": "Local Heat & Anti-inflammatory Therapy",
        "action_level_desc": "Apply warm compresses; brief course of NSAIDs; avoid heavy lifting.",
        "key_symptoms": ["pleuritic_chest_stitch", "chest_tightness_exertion"],
        "unreported_common": ["low_grade_fever", "radiating_arm_jaw_pain", "cold_diaphoresis"],
        "prevention": "Gradual warm-up before chest press exercises, core stretching."
    },
    {
        "id": "reactive_arthralgia",
        "name": "Post-Infectious Reactive Polyarthralgia",
        "simple_name": "Post-Viral Joint Pain",
        "simple_explanation": "Temporary joint swelling and soreness in knees, wrists, or ankles following a recent viral or bacterial infection.",
        "icd10": "M13.8",
        "primary_system": "Synovial Capsule & Tendon Sheaths",
        "natural_duration": "2 — 6 Weeks",
        "action_level": "Joint Rest & Low-Impact Mobility",
        "action_level_desc": "Maintain gentle range of motion; avoid high-impact joint loading; consult rheumatology if persistent.",
        "key_symptoms": ["knee_arthralgia_joint_pain", "morning_joint_stiffness", "joint_effusion_swelling", "generalized_myalgia"],
        "unreported_common": ["retrosternal_chest_pressure", "anosmia_loss_smell"],
        "prevention": "Full convalescence following viral infections."
    },
    {
        "id": "post_viral_fatigue",
        "name": "Post-Viral Asthenia & Immune Clearance Fatigue",
        "simple_name": "Post-Viral Fatigue",
        "simple_explanation": "Lingering low energy, brain fog, and muscle weakness that persists for weeks after your body clears a viral illness.",
        "icd10": "R53.82",
        "primary_system": "Neuro-Endocrine-Immune Axis",
        "natural_duration": "2 — 4 Weeks post-infection",
        "action_level": "Pacing & Graduated Activity",
        "action_level_desc": "Energy conservation principles; prioritize restorative sleep; do not push through severe crashes.",
        "key_symptoms": ["physical_fatigue_malaise", "cognitive_fog_fatigue", "generalized_myalgia"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "diarrhea_enteritis", "radiating_arm_jaw_pain"],
        "prevention": "Avoid premature strenuous exertion following acute febrile viral illnesses."
    },
    {
        "id": "asthma_bronchospasm",
        "name": "Acute Asthmatic Airway Hyperreactivity",
        "simple_name": "Asthma Flare-Up",
        "simple_explanation": "Temporary narrowing and swelling of bronchial airways, causing expiatory wheezing, chest tightness, and sudden shortness of breath.",
        "icd10": "J45.901",
        "primary_system": "Bronchial Airway Smooth Muscle",
        "natural_duration": "Acute / Hours to Days",
        "action_level": "Inhaled Bronchodilator (Rescue Inhaler)",
        "action_level_desc": "Use prescribed albuterol inhaler; eliminate exposure to dust, smoke, or cold air.",
        "key_symptoms": ["wheezing_bronchospasm", "dyspnea_shortness_breath", "chest_tightness_exertion", "persistent_dry_cough"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "diarrhea_enteritis", "anosmia_loss_smell"],
        "prevention": "Identify environmental triggers, carry rescue inhaler."
    },
    {
        "id": "copd_exacerbation",
        "name": "Chronic Obstructive Airway Exacerbation",
        "simple_name": "COPD / Chronic Bronchitis Flare",
        "simple_explanation": "A sudden worsening of long-term breathing difficulty with increased sputum production and wheezing.",
        "icd10": "J44.1",
        "primary_system": "Lower Pulmonary Parenchyma",
        "natural_duration": "1 — 2 Weeks",
        "action_level": "Clinical Evaluation & Nebulizer Therapy",
        "action_level_desc": "Consult pulmonologist; monitor pulse oximetry; evaluate requirement for oral steroids or antibiotics.",
        "key_symptoms": ["productive_cough_sputum", "dyspnea_shortness_breath", "wheezing_bronchospasm", "physical_fatigue_malaise"],
        "unreported_common": ["frontal_tension_headache", "epigastric_pyrosis_reflux"],
        "prevention": "Complete avoidance of air pollutants and tobacco smoke, annual pneumococcal vaccines."
    },
    {
        "id": "angina_coronary_strain",
        "name": "Acute Myocardial Ischemic Strain (Angina)",
        "simple_name": "Heart Angina / Reduced Cardiac Blood Flow",
        "simple_explanation": "Tightness or pressure behind the breastbone caused by temporarily reduced blood flow to the heart muscle, often during physical exertion.",
        "icd10": "I20.9",
        "primary_system": "Coronary Arterial Vasculature",
        "natural_duration": "Minutes to Hours (Requires emergency medical assessment)",
        "action_level": "Urgent Cardiac Medical Evaluation",
        "action_level_desc": "Rest immediately; seek emergency medical evaluation if chest pressure persists beyond 5 minutes.",
        "key_symptoms": ["retrosternal_chest_pressure", "radiating_arm_jaw_pain", "cold_diaphoresis", "dyspnea_shortness_breath"],
        "unreported_common": ["anosmia_loss_smell", "diarrhea_enteritis", "sore_throat_pharyngitis"],
        "prevention": "Heart-healthy diet, blood pressure control, regular low-impact exercise."
    },
    {
        "id": "paroxysmal_tachycardia",
        "name": "Paroxysmal Supraventricular Tachycardia",
        "simple_name": "Rapid / Fluttering Heartbeat",
        "simple_explanation": "Sudden episodes of a fast, pounding, or fluttering heartbeat originating from electrical signals in the upper heart chambers.",
        "icd10": "I47.1",
        "primary_system": "Cardiac Conduction System",
        "natural_duration": "Episodes lasting 5 minutes to several hours",
        "action_level": "Vagal Maneuvers & ECG Monitoring",
        "action_level_desc": "Perform vagal maneuvers (bearing down); seek prompt medical evaluation if dizziness or chest pressure occurs.",
        "key_symptoms": ["palpitations_tachycardia", "dizziness_vertigo", "physical_fatigue_malaise", "chest_tightness_exertion"],
        "unreported_common": ["productive_cough_sputum", "diarrhea_enteritis"],
        "prevention": "Limit caffeine, alcohol, and stress triggers."
    },
    {
        "id": "pots_syndrome",
        "name": "Postural Orthostatic Tachycardia Syndrome (POTS)",
        "simple_name": "Standing Dizziness / POTS",
        "simple_explanation": "A condition where standing up causes an unusually rapid jump in heart rate, lightheadedness, shakiness, and fatigue.",
        "icd10": "G90.5",
        "primary_system": "Autonomic Nervous System",
        "natural_duration": "Chronic episodic management",
        "action_level": "Hydration, Electrolytes & Compression Wear",
        "action_level_desc": "Increase daily fluid and salt intake under guidance; wear waist-high compression garments.",
        "key_symptoms": ["dizziness_vertigo", "palpitations_tachycardia", "cognitive_fog_fatigue", "cold_diaphoresis"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "productive_cough_sputum"],
        "prevention": "Gradual standing positions, cool ambient temperatures."
    },
    {
        "id": "peptic_ulcer",
        "name": "Acute Peptic Ulcer Mucosal Erosion",
        "simple_name": "Stomach Ulcer Pain",
        "simple_explanation": "A painful sore on the lining of your stomach or upper small intestine causing gnawing stomach pain, burning, and stomach fullness.",
        "icd10": "K27.9",
        "primary_system": "Gastroduodenal Mucosa",
        "natural_duration": "2 — 4 Weeks with therapy",
        "action_level": "Proton Pump Inhibitor (PPI) & H. Pylori Check",
        "action_level_desc": "Avoid NSAIDs like ibuprofen; visit doctor for H. Pylori testing and acid reduction therapy.",
        "key_symptoms": ["epigastric_pyrosis_reflux", "nausea_emesis", "early_satiety_dyspepsia", "bloating_meteorism"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "wheezing_bronchospasm"],
        "prevention": "Avoid frequent NSAID usage, limit alcohol and spicy foods."
    },
    {
        "id": "ibs_spasmodic",
        "name": "Irritable Bowel Syndrome (Spasmodic)",
        "simple_name": "Irritable Bowel Syndrome (IBS)",
        "simple_explanation": "A common intestinal disorder causing periodic stomach cramping, bloating, gas, and alternating bouts of diarrhea or constipation.",
        "icd10": "K58.9",
        "primary_system": "Enteric Neuromuscular Plexus",
        "natural_duration": "Chronic recurrent episodes",
        "action_level": "Low-FODMAP Diet & Antispasmodic",
        "action_level_desc": "Track dietary triggers; increase soluble fiber intake; stress reduction techniques.",
        "key_symptoms": ["abdominal_cramping", "bloating_meteorism", "diarrhea_enteritis", "constipation_slow_transit"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "pleuritic_chest_stitch"],
        "prevention": "Regular meal timing, managing stress levels."
    },
    {
        "id": "acute_cholecystitis",
        "name": "Acute Biliary Cholecystitis / Gallbladder Inflammation",
        "simple_name": "Gallbladder Attack / Pain",
        "simple_explanation": "Inflammation of the gallbladder, often caused by gallstones blocking bile flow, resulting in sharp pain in the upper right stomach after fatty meals.",
        "icd10": "K81.0",
        "primary_system": "Biliary Tract & Gallbladder",
        "natural_duration": "Acute episode requiring medical evaluation",
        "action_level": "Clinical Abdominal Exam & Ultrasound",
        "action_level_desc": "Seek medical evaluation; avoid high-fat meals; obtain abdominal ultrasound.",
        "key_symptoms": ["ruq_hepatic_tenderness", "nausea_emesis", "low_grade_fever", "abdominal_cramping"],
        "unreported_common": ["anosmia_loss_smell", "persistent_dry_cough"],
        "prevention": "Maintain low-fat diet, gradual weight loss."
    },
    {
        "id": "bppv_vertigo",
        "name": "Benign Paroxysmal Positional Vertigo (BPPV)",
        "simple_name": "Inner Ear Dizziness (Vertigo)",
        "simple_explanation": "A sudden spinning sensation triggered by head movements, caused by tiny calcium crystals shifting inside the inner ear.",
        "icd10": "H81.10",
        "primary_system": "Semicircular Canal Otoliths",
        "natural_duration": "Days to Weeks",
        "action_level": "Epley Canalith Repositioning Maneuver",
        "action_level_desc": "Perform canalith repositioning exercises under medical or physical therapy guidance.",
        "key_symptoms": ["dizziness_vertigo", "nausea_emesis", "cognitive_fog_fatigue"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "productive_cough_sputum"],
        "prevention": "Avoid sudden rapid head tilt movements during acute recovery."
    },
    {
        "id": "fibromyalgia_flare",
        "name": "Fibromyalgia Central Sensitization Flare",
        "simple_name": "Fibromyalgia Muscle & Body Pain Flare",
        "simple_explanation": "A widespread flare of deep muscle pain, tenderness, unrefreshing sleep, and brain fog caused by heightened pain signal processing.",
        "icd10": "M79.7",
        "primary_system": "Central Pain Processing Pathways",
        "natural_duration": "Recurrent flares (Days to Weeks)",
        "action_level": "Gentle Warmth, Pacing & Sleep Hygiene",
        "action_level_desc": "Apply warm baths or heating pads; maintain gentle movement; prioritize structured sleep routines.",
        "key_symptoms": ["generalized_myalgia", "physical_fatigue_malaise", "cognitive_fog_fatigue", "morning_joint_stiffness"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "productive_cough_sputum"],
        "prevention": "Pacing daily activities, stress reduction, warm evening routines."
    },
    {
        "id": "osteoarthritis_flare",
        "name": "Osteoarthritis Degenerative Joint Flare",
        "simple_name": "Osteoarthritis Joint Pain",
        "simple_explanation": "Wear-and-tear inflammation of joint cartilage causing deep joint aching, morning stiffness, and swelling in knees, hips, or hands.",
        "icd10": "M19.90",
        "primary_system": "Articular Hyaline Cartilage",
        "natural_duration": "Persists with physical activity",
        "action_level": "Topical Anti-inflammatory & Low-Impact Exercise",
        "action_level_desc": "Use topical NSAID gel; engage in low-impact swimming or cycling; apply ice or heat packs.",
        "key_symptoms": ["knee_arthralgia_joint_pain", "morning_joint_stiffness", "joint_effusion_swelling", "shoulder_glenohumeral_limitation"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "diarrhea_enteritis"],
        "prevention": "Maintain joint-friendly physical activity, weight management."
    },
    {
        "id": "iron_deficiency_anemia",
        "name": "Iron Deficiency Anemia & Microcytic Strain",
        "simple_name": "Iron Deficiency Anemia",
        "simple_explanation": "A drop in healthy red blood cells from low body iron stores, causing pale skin, cold hands, rapid fatigue, and exertional breathlessness.",
        "icd10": "D50.9",
        "primary_system": "Hematopoietic Red Cell Mass",
        "natural_duration": "1 — 3 Months of nutritional supplementation",
        "action_level": "Blood Panel & Oral Iron Therapy",
        "action_level_desc": "Obtain complete blood count and serum ferritin test; take elemental iron supplements with Vitamin C.",
        "key_symptoms": ["physical_fatigue_malaise", "cognitive_fog_fatigue", "dizziness_vertigo", "palpitations_tachycardia", "dyspnea_shortness_breath"],
        "unreported_common": ["uncontrolled_hyperpyrexia", "diarrhea_enteritis"],
        "prevention": "Iron-rich diet (spinach, lentils, red meat), avoid tea/coffee directly with meals."
    },
    {
        "id": "acute_mononucleosis",
        "name": "Epstein-Barr Virus Infectious Mononucleosis",
        "simple_name": "Mono (Glandular Fever)",
        "simple_explanation": "A common viral illness (Epstein-Barr Virus) causing extreme fatigue, severe sore throat, high fever, and swollen lymph nodes in the neck.",
        "icd10": "B27.0",
        "primary_system": "B-Lymphocyte Lymphoreticular System",
        "natural_duration": "2 — 4 Weeks",
        "action_level": "Abundant Rest & Avoid Contact Sports",
        "action_level_desc": "Rest completely; avoid contact sports for 4 weeks due to spleen enlargement risk; hydrate well.",
        "key_symptoms": ["sore_throat_pharyngitis", "lymphadenopathy_cervical", "physical_fatigue_malaise", "low_grade_fever", "generalized_myalgia"],
        "unreported_common": ["epigastric_pyrosis_reflux", "constipation_slow_transit"],
        "prevention": "Avoid sharing water bottles, utensils, or lip balm."
    },
    {
        "id": "dengue_fever_syndrome",
        "name": "Dengue Arboviral Febrile Syndrome",
        "simple_name": "Dengue Fever",
        "simple_explanation": "A mosquito-borne viral infection causing high fever, severe pain behind the eyes, intense joint/bone aches, and profound weakness.",
        "icd10": "A90",
        "primary_system": "Vascular Endothelium & Platelet Cascade",
        "natural_duration": "5 — 7 Days (Requires monitoring of platelet count)",
        "action_level": "Hydration & Platelet Count Surveillance",
        "action_level_desc": "Take paracetamol for fever; avoid aspirin or ibuprofen; monitor full blood count for platelet drops.",
        "key_symptoms": ["uncontrolled_hyperpyrexia", "generalized_myalgia", "knee_arthralgia_joint_pain", "shivering_rigors_chills", "physical_fatigue_malaise"],
        "unreported_common": ["productive_cough_sputum", "hoarseness_stridor"],
        "prevention": "Mosquito repellent, standing water elimination, protective clothing."
    },
    {
        "id": "uti_systemic_flare",
        "name": "Upper Urinary Tract Inflammatory Response (UTI)",
        "simple_name": "Urinary Tract Infection (UTI) / Kidney Strain",
        "simple_explanation": "A bacterial infection of the urinary tract causing lower stomach discomfort, fever, chills, and back or flank soreness.",
        "icd10": "N39.0",
        "primary_system": "Urogenital Mucosal Epithelium",
        "natural_duration": "3 — 7 Days with targeted antibiotics",
        "action_level": "Urinalysis & Antibiotic Course",
        "action_level_desc": "Visit clinic for urinalysis and targeted antibiotic prescription; drink plenty of water.",
        "key_symptoms": ["low_grade_fever", "lumbar_paraspinal_strain", "abdominal_cramping", "shivering_rigors_chills", "physical_fatigue_malaise"],
        "unreported_common": ["persistent_dry_cough", "anosmia_loss_smell"],
        "prevention": "Adequate daily water intake, prompt voiding after activity."
    }
]